# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']=""


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to firebase"
  lane :firebase do |options|

    clear_derived_data
    clean_build_artifacts
  
    build_app(
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "com.reactnativedevops" => "Provisioning Profile react native depops"
        }
      }
    )
 
    puts "+---------------------------------+".bold.blue
    puts "|-- FIREBASE_CLI_TOKEN: #{ENV['FIREBASE_CLI_TOKEN']} 🚀 --|".bold.blue
    puts "|-- FIREBASE_APP_ID: #{ENV['FIREBASE_APP_ID']} 🚀 --|".bold.blue
    puts "+---------------------------------+".bold.blue
   
    
     firebase_app_distribution(
       app: ENV['FIREBASE_APP_ID'],
       firebase_cli_token: ENV['FIREBASE_CLI_TOKEN']
     )
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do |options|
  
      clear_derived_data
      clean_build_artifacts
  
      build_app(
        scheme: "Release",
        export_options: {
          method: "app-store",
          provisioningProfiles: { 
            "com.reactnativedevops" => "Provisioningdevopsstore"
          }
        }
      )
  
      upload_to_testflight(
        notify_external_testers:true,
        skip_waiting_for_build_processing:true
  
      )
  
    end


end

